name: Build and push frontend image

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract git short sha
        id: gitmeta
        run: echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile.frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:${{ steps.gitmeta.outputs.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
